#!/bin/bash
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     ATIVACÃO BOT SSH TESTE     \E[0m"
    echo -e "\n\033[1;31m QUANDO REINICIAR A VPS, SERA PRECISO INSERIR \033[1;33m "
    echo -e "\033[1;31m O TOKEN NOVAMENTE INSERINDO O COMANDO: \033[1;32mbotteste\033[0m"
    echo -ne "\n\033[1;32m INFORME O TOKEN\033[1;37m: "; read token
    echo ""
    echo -ne "\n\033[1;32m TEMPO DE DURAÇÃO EM HORAS\033[1;37m: "; read hora
    echo ""
    echo -ne "\n\033[1;32m MENSAGEM DE BOAS VINDAS\033[1;37m: "; read boasvindas
    echo ""
    echo -ne "\n\033[1;32m MENSAGEM AO CRIAR CONTA SSH\033[1;37m: "; read tentarcriar
    echo ""
    echo -ne "\n\033[1;32m INFORME O NOME BOTÃO 1\033[1;37m: "; read bnt1
    echo ""
    echo -ne "\n\033[1;32m INFORME O NOME BOTÃO 2\033[1;37m: "; read bnt2
    echo ""
    echo -ne "\n\033[1;32m INFORME O LINK DO BOTÃO 2\033[1;37m: "; read link2
    echo ""
    echo -ne "\n\033[1;32m INFORME O NOME BOTÃO 3\033[1;37m: "; read bnt3
    echo ""
    echo -ne "\n\033[1;32m INFORME O LINK DO BOTÃO 3\033[1;37m: "; read link3
    echo ""
    cd $HOME/BOT
    screen -dmS bot_teste ./botssh $token $hora $boasvindas $tentarcriar $bnt1 $bnt2 $link2 $bnt3 $link3 > /dev/null 2>&1
    [[ $(grep -wc "bot_teste" /etc/autostart) = '0' ]] && {
                echo -e "ps x | grep 'bot_teste' | grep -v 'grep' || cd /root/BOT && sudo screen -dmS bot_teste ./botssh $token $hora $boasvindas $tentarcriar $bnt1 $bnt2 $link2 $bnt3 $link3 && cd $HOME" >>/etc/autostart
            } || {
                sed -i '/bot_teste/d' /etc/autostart
                echo -e "ps x | grep 'bot_teste' | grep -v 'grep' || cd /root/BOT && sudo screen -dmS bot_teste ./botssh $token $hora $boasvindas $tentarcriar $bnt1 $bnt2 $link2 $bnt3 $link3 && cd $HOME" >>/etc/autostart
            }
    clear && echo "BOT ATIVADO"
} || {
    screen -r -S "bot_teste" -X quit
    clear && echo "BOT DESATIVADO"
}