#!/bin/bash
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     ATIVACÃO BOT SSH TESTE     \E[0m"
    echo -e "\n\033[1;31m QUANDO REINICIAR A VPS, SERA PRECISO INSERIR \033[1;33m "
    echo -e "\033[1;31m O TOKEN NOVAMENTE INSERINDO O COMANDO: \033[1;32mbotteste\033[0m"
    echo -ne "\n\033[1;32m INFORME O TOKEN\033[1;37m: "; read token
    echo -e ""
    echo -ne "\n\033[1;32m NOME DO BOTÃO 1\033[1;37m: "; read btn1
    echo -e ""
    echo -ne "\n\033[1;32m NOME DO BOTÃO 2\033[1;37m: "; read btn2
    echo -e ""
    echo -ne "\n\033[1;32m LINK DO BOTÃO 2\033[1;37m: "; read btnlink2
    echo -e ""
    echo -ne "\n\033[1;32m NOME DO BOTÃO 3\033[1;37m: "; read btn3
    echo -e ""
    echo -ne "\n\033[1;32m LINK DO BOTÃO 3\033[1;37m: "; read btnlink3
    echo -e ""
    echo -ne "\n\033[1;32m TEMPO DE DURAÇÃO\033[1;37m: "; read tempo
    echo -e ""
    echo -ne "\n\033[1;32m MENSAGEM DE BOAS VINDAS\033[1;37m: "; read msg
    cd $HOME/BOT
    screen -dmS bot_teste ./botssh $token $btn1 $btn2 $btnlink2 $btn3 $btnlink3 $tempo $msg> /dev/null 2>&1
[[ $(grep -wc "bot_teste" /etc/autostart) = '0' ]] && {
                echo -e "ps x | grep 'bot_teste' | grep -v 'grep' || cd /root/BOT && sudo screen -dmS bot_teste ./botssh $token $btn1 $btn2 $btnlink2 $btn3 $btnlink3 $tempo $msg && cd $HOME" >>/etc/autostart
            } || {
                sed -i '/bot_teste/d' /etc/autostart
                echo -e "ps x | grep 'bot_teste' | grep -v 'grep' || cd /root/BOT && sudo screen -dmS bot_teste ./botssh $token $btn1 $btn2 $btnlink2 $btn3 $btnlink3 $tempo $msg && cd $HOME" >>/etc/autostart
            }
    clear && echo "BOT ATIVADO"
} || {
    screen -r -S "bot_teste" -X quit
    clear && echo "BOT DESATIVADO"
}